services:
  # Backend Service: Spring Boot
  - type: web
    name: ghibli-backend-shahvez
    env: java
    rootDir: ghibliaibackend
    buildCommand: "mvn clean install"
    startCommand: "java -jar target/ghibliaibackend-0.0.1-SNAPSHOT.jar"
    plan: free
    envVars:
      - key: STABILITY_API_KEY
        sync: false 

  # Frontend Service: React Static Site
  - type: static site
    name: ghibli-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: ghibli-backend-shahvez
          property: url